Web/Controllers/GroupTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchematicsModel.Dictionary;
using Newtonsoft.Json;
using SchematicsModel.Storage;

namespace Web.Controllers
{
    [RoutePrefix("api/group-types")]
    public class GroupTypesController : BaseSchematicsController<GroupType>
    {
        protected override SchematicsModel.Storage.IStorageCollection<GroupType> GetDataSet()
        {
            return GetDictionaryStorage().GroupTypes;
        }

        public override ActionResult Index()
        {
            return base.Index();
        }

        protected override void Commit(IStorageCollection<GroupType> items)
        {
            items.Commit();
        }

        [HttpGet]
        [Route("list")]
        public override ActionResult GetList()
        {
            return base.GetList();
        }


        [HttpGet]
        [Route("item")]
        public override ActionResult GetItem(string id)
        {
            return base.GetItem(id);
        }


        [HttpPut]
        [Route("add")]
        public override ActionResult Add()
        {
            return base.Add();
        }
        
        [HttpPost]
        [Route("update")]
        public override ActionResult Update(string id)
        {
            return base.Update(id);
        }
        
        [HttpDelete]
        [Route("delete")]
        public override ActionResult Delete(string id)
        {
            return base.Delete(id);
        }
    }
}

Web/Controllers/LinkTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchematicsModel.Dictionary;
using Newtonsoft.Json;
using SchematicsModel.Storage;

namespace Web.Controllers
{
    [RoutePrefix("api/link-types")]
    public class LinkTypesController : BaseSchematicsController<LinkType>
    {
        protected override SchematicsModel.Storage.IStorageCollection<LinkType> GetDataSet()
        {
            return GetDictionaryStorage().LinkTypes;
        }

        public override ActionResult Index()
        {
            return base.Index();
        }

        protected override void Commit(IStorageCollection<LinkType> items)
        {
            items.Commit();
        }

        [HttpGet]
        [Route("list")]
        public override ActionResult GetList()
        {
            return base.GetList();
        }


        [HttpGet]
        [Route("item")]
        public override ActionResult GetItem(string id)
        {
            return base.GetItem(id);
        }


        [HttpPut]
        [Route("add")]
        public override ActionResult Add()
        {
            return base.Add();
        }
        
        [HttpPost]
        [Route("update")]
        public override ActionResult Update(string id)
        {
            return base.Update(id);
        }
        
        [HttpDelete]
        [Route("delete")]
        public override ActionResult Delete(string id)
        {
            return base.Delete(id);
        }
    }
}

Web/Controllers/NodeTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchematicsModel.Dictionary;
using Newtonsoft.Json;
using SchematicsModel.Storage;

namespace Web.Controllers
{
    [RoutePrefix("api/node-types")]
    public class NodeTypesController : BaseSchematicsController<NodeType>
    {
        protected override SchematicsModel.Storage.IStorageCollection<NodeType> GetDataSet()
        {
            return GetDictionaryStorage().NodeTypes;
        }

        public override ActionResult Index()
        {
            return base.Index();
        }

        protected override void Commit(IStorageCollection<NodeType> items)
        {
            items.Commit();
        }

        [HttpGet]
        [Route("list")]
        public override ActionResult GetList()
        {
            return base.GetList();
        }


        [HttpGet]
        [Route("item")]
        public override ActionResult GetItem(string id)
        {
            return base.GetItem(id);
        }


        [HttpPut]
        [Route("add")]
        public override ActionResult Add()
        {
            return base.Add();
        }
        
        [HttpPost]
        [Route("update")]
        public override ActionResult Update(string id)
        {
            return base.Update(id);
        }
        
        [HttpDelete]
        [Route("delete")]
        public override ActionResult Delete(string id)
        {
            return base.Delete(id);
        }
    }
}

Web/Controllers/StylesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchematicsModel.Styles;
using Newtonsoft.Json;
using SchematicsModel.Storage;

namespace Web.Controllers
{
    [RoutePrefix("api/styles")]
    public class StylesController : BaseSchematicsController<Style>
    {
        protected override SchematicsModel.Storage.IStorageCollection<Style> GetDataSet()
        {
            return GetStylesStorage().Styles;
        }

        public override ActionResult Index()
        {
            return base.Index();
        }

        protected override void Commit(IStorageCollection<Style> items)
        {
            items.Commit();
        }


        [HttpGet]
        [Route("list")]
        public override ActionResult GetList()
        {
            try
            {
                var result = GetDataSet().DataSet.Select(i => new { id = i.Id, name = i.Name, @for = i.For, zIndex = i.ZIndex }).OrderBy(i => i.name).ToList();
                return Json(new { list = result }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return ErrorResult(ex);
            }
        }


        [HttpGet]
        [Route("item")]
        public override ActionResult GetItem(string id)
        {
            return base.GetItem(id);
        }


        [HttpPut]
        [Route("add")]
        public override ActionResult Add()
        {
            return base.Add();
        }
        
        [HttpPost]
        [Route("update")]
        public override ActionResult Update(string id)
        {
            return base.Update(id);
        }
        
        [HttpDelete]
        [Route("delete")]
        public override ActionResult Delete(string id)
        {
            return base.Delete(id);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Схематика</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/schematics")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/schematics")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Схематика", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>*@
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Схема", "Schematics", "Home")</li>
                    <li>@Html.ActionLink("Стили", "Styles", "Home")</li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Справочники <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Типы узлов", "NodeTypes", "Home")</li>
                            <li>@Html.ActionLink("Типы связей", "LinkTypes", "Home")</li>
                            <li>@Html.ActionLink("Типы групп", "GroupTypes", "Home")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Состояния", "States", "Home")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Схематика</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>